spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    type: org.apache.commons.dbcp2.BasicDataSource

    dbcp2:
      initial-size: 10
      max-idle: 50
      min-idle: 20
      validation-query: SELECT 1
      default-auto-commit: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


nhn:
  cloud:
    keyManager:
      appkey: 2SxwmBzUfnqJaA2A
      storeKeyId: e0a81fc89a1d4c5196df53d3fdab0f64
      couponKeyId: 62954fd4bba04501a7059459ae11a56d
      batchKeyId: 96363c48ca6f4fe186cb7b3a144165f0
      userAccessKeyId: J9VxQFQEsmerR1n7FeJ6
      secretAccessKey: zZEVopUHt6dxgRMt
