spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 1
      max-idle: 2
      min-idle: 1
      validation-query: SELECT 1
      default-auto-commit: true
      max-total: 2

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

  #로그 크러쉬 정보
  logstash:
    host: 133.186.241.167
    platform: NovaBook-Batch-Prod
    url: https://api-logncrash.cloud.toast.com/v2/log
    projectName: Xyx7DoyszcG66ULx
    projectVersion: 1.0.0
    logVersion: v2
    logSource: http
    logType: log
    secretKey: JsGDL5oTWPImKY8nag9igsUAdnUOvLMI


nhn:
  cloud:
    keyManager:
      appkey: 2SxwmBzUfnqJaA2A
      storeKeyId: e0a81fc89a1d4c5196df53d3fdab0f64
      couponKeyId: 62954fd4bba04501a7059459ae11a56d
      batchKeyId: 96363c48ca6f4fe186cb7b3a144165f0
      userAccessKeyId: J9VxQFQEsmerR1n7FeJ6
      secretAccessKey: zZEVopUHt6dxgRMt
