spring:
  datasource:
    coupon:
      jdbc-url: jdbc:mysql://133.186.241.167:3306/be6_supernova_coupon_dev
      username: be6_supernova
      password: Hv-]JRIyCw[[9O18
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: org.apache.commons.dbcp2.BasicDataSource
    store:
      jdbc-url: jdbc:mysql://133.186.241.167:3306/be6_supernova_dev
      username: be6_supernova
      password: Hv-]JRIyCw[[9O18
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: org.apache.commons.dbcp2.BasicDataSource
    batch:
      jdbc-url: jdbc:mysql://133.186.241.167:3306/be6_supernova_batch
      username: be6_supernova
      password: Hv-]JRIyCw[[9O18
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 10
      max-idle: 50
      min-idle: 20
      validation-query: SELECT 1
      default-auto-commit: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

store:
  service:
    url: http://localhost:8090

coupon:
  service:
    url: http://localhost:8070